# Generated by Django 4.1.7 on 2023-02-26 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_menu_tags_restaurant_order_menu_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='dish_image',
            field=models.ImageField(upload_to='<django.db.models.query_utils.DeferredAttribute object at 0x000001B4E43CC1C0>/dishes/'),
        ),
    ]
