# Generated by Django 4.1.7 on 2023-02-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_menu_dish_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='dish_desc',
            field=models.TextField(blank=True),
        ),
    ]
